name: Deploy Subsocial Docs to dappforce.github.io

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn install
      - name: Build Docusaurus
        run: yarn build
      - name: Deploy build directory to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: dappforce/dappforce.github.io
          publish_dir: ./build
